//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnt.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cay()
        {
            this.ChiTietCay_KH = new HashSet<ChiTietCay_KH>();
            this.ChiTietNhapGiongs = new HashSet<ChiTietNhapGiong>();
            this.NongSans = new HashSet<NongSan>();
        }
    
        public int MaLoaiCay { get; set; }
        public string TenCay { get; set; }
        public int SoLuong { get; set; }
        public string MuaThuHoach { get; set; }
        public System.DateTime NamGieoDau { get; set; }
        public string KhuVuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietCay_KH> ChiTietCay_KH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhapGiong> ChiTietNhapGiongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NongSan> NongSans { get; set; }
    }
}
