//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnt.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTiet_TH
    {
        public int MaNS { get; set; }
        public int MaPhieu { get; set; }
        public double SanLuongThuHoach { get; set; }
    
        public virtual NongSan NongSan { get; set; }
        public virtual PhieuNhapN PhieuNhapN { get; set; }
    }
}
