//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnt.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKHBonPhan
    {
        public int MaPB { get; set; }
        public int MaKH { get; set; }
        public Nullable<double> LieuLuong { get; set; }
        public bool HoanThanh { get; set; }
    
        public virtual KeHoach KeHoach { get; set; }
        public virtual PhanBon PhanBon { get; set; }
    }
}
