//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnt.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietXuat_NS
    {
        public int MaPhieuXuat { get; set; }
        public int MaNS { get; set; }
        public double SanLuong { get; set; }
        public double DonGia { get; set; }
    
        public virtual NongSan NongSan { get; set; }
        public virtual PhieuXuat PhieuXuat { get; set; }
    }
}
