//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnt.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHoaDon { get; set; }
        public System.DateTime NgayMua { get; set; }
        public double ThanhTien { get; set; }
        public int MaKH { get; set; }
        public int MaPhieuXuat { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual PhieuXuat PhieuXuat { get; set; }
    }
}
