//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnt.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeHoach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KeHoach()
        {
            this.ChiTietCay_KH = new HashSet<ChiTietCay_KH>();
            this.ChiTietKHBonPhans = new HashSet<ChiTietKHBonPhan>();
            this.ChiTietKHDungThuocs = new HashSet<ChiTietKHDungThuoc>();
            this.PhieuNhapNS = new HashSet<PhieuNhapN>();
        }
    
        public int MaKeHoach { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayThucThien { get; set; }
        public int TienDoHoanThanh { get; set; }
        public string ChuThich { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietCay_KH> ChiTietCay_KH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKHBonPhan> ChiTietKHBonPhans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKHDungThuoc> ChiTietKHDungThuocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhapN> PhieuNhapNS { get; set; }
    }
}
