//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnt.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNhap()
        {
            this.ChiTietNhap_PB = new HashSet<ChiTietNhap_PB>();
            this.ChiTietNhap_TBV = new HashSet<ChiTietNhap_TBV>();
            this.ChiTietNhapGiongs = new HashSet<ChiTietNhapGiong>();
        }
    
        public int MaPhieuNhap { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public double ThanhTien { get; set; }
        public int MaNCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhap_PB> ChiTietNhap_PB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhap_TBV> ChiTietNhap_TBV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhapGiong> ChiTietNhapGiongs { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
