//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlnt.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNTEntities1 : DbContext
    {
        public QLNTEntities1()
            : base("name=QLNTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cay> Cays { get; set; }
        public virtual DbSet<ChiTiet_TH> ChiTiet_TH { get; set; }
        public virtual DbSet<ChiTietCay_KH> ChiTietCay_KH { get; set; }
        public virtual DbSet<ChiTietKHBonPhan> ChiTietKHBonPhans { get; set; }
        public virtual DbSet<ChiTietKHDungThuoc> ChiTietKHDungThuocs { get; set; }
        public virtual DbSet<ChiTietNhap_PB> ChiTietNhap_PB { get; set; }
        public virtual DbSet<ChiTietNhap_TBV> ChiTietNhap_TBV { get; set; }
        public virtual DbSet<ChiTietNhapGiong> ChiTietNhapGiongs { get; set; }
        public virtual DbSet<ChiTietXuat_NS> ChiTietXuat_NS { get; set; }
        public virtual DbSet<ChiTietXuat_PB> ChiTietXuat_PB { get; set; }
        public virtual DbSet<ChiTietXuat_TBV> ChiTietXuat_TBV { get; set; }
        public virtual DbSet<DoDoc> DoDocs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KeHoach> KeHoaches { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NongSan> NongSans { get; set; }
        public virtual DbSet<PhanBon> PhanBons { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<PhieuNhapN> PhieuNhapNS { get; set; }
        public virtual DbSet<PhieuXuat> PhieuXuats { get; set; }
        public virtual DbSet<ThuocBaoVeTV> ThuocBaoVeTVs { get; set; }
        public virtual DbSet<ViTri> ViTris { get; set; }
    }
}
